/* eslint-disable @next/next/no-img-element */ 
import Head from 'next/head'   

export default function MetaComponent(props:any) {
    return(  
        <Head>
            <title>PSC | Brokrete</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />             
        </Head> 
    )
}
 